# Generated by Django 3.2.7 on 2023-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assgn1', '0003_auto_20230505_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, null=True)),
                ('author', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
