# Generated by Django 3.2.7 on 2023-05-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assgn1', '0004_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
